package day7

import Day7._

class Day7Suite extends munit.FunSuite:

  val input = """.......S.......
                |...............
                |.......^.......
                |...............
                |......^.^......
                |...............
                |.....^.^.^.....
                |...............
                |....^.^...^....
                |...............
                |...^.^...^.^...
                |...............
                |..^...^.....^..
                |...............
                |.^.^.^.^.^...^.
                |...............""".stripMargin

  test("Day7 part1"):
    assertEquals(part1(input), 21)

  test("Day7 part2"):
    assertEquals(part2(input), 40L)

